name: build-image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build & push image
      run: |
        IMAGE_NAME=${GITHUB_REPOSITORY#sksat/}:${GITHUB_REF#refs/heads/}
        docker build . --tag ghcr.io/${GITHUB_REPOSITORY}/${IMAGE_NAME}
        docker push ghcr.io/${GITHUB_REPOSITORY}/${IMAGE_NAME}
